name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: generate-activity-graph
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Activity Graph SVG
        uses: ashutoshgvarshney/github-readme-activity-graph@3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: assets/activity.svg
          theme: tokyo-night
          
      - name: Commit & Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/activity.svg
          git commit -m "chore: auto-update animated activity graph telemetry" || exit 0
          git push origin main
